discord:
    token: NTQ4ODk4NDYzNjIzMTUxNjI4.D1WltA.Joag4ki4idaopmUI9SuVS3ZfHYs
spring:
    datasource:
        url: jdbc:h2:mem:testdb;Mode=Oracle;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    h2:
        console:
            enabled: false
    jpa:
        hibernate:
            ddl-auto: create-drop
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        show-sql: false
