################################################################
# Spring-Data properties
################################################################
# Always force db migration

spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

#flyway.enabled: true
#flyway.locations: classpath:db/migration