dasLigaBot:
  loginBaseUrl: "http://dasLiga.ddns.us:8080/linkBattleNet"
  dasLigaServer:
    id: "168007460173381632"

spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

discord:
  authorUserId: "116296552204599298"

#flyway.enabled: true
#flyway.locations: classpath:db/migration